<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArmadaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('armada')->insert([
            // ========== ANGKUTAN / BARANG ==========
            [
                'no_plat' => 'B 1001 PK',
                'jenis_kendaraan' => 'Pickup Bak',
                'kapasitas' => '1.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'pickup-bak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 1002 PK',
                'jenis_kendaraan' => 'Pickup Box',
                'kapasitas' => '1.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'pickup-box.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 2001 CDE',
                'jenis_kendaraan' => 'CDE Bak',
                'kapasitas' => '2.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'cde-bak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 2002 CDE',
                'jenis_kendaraan' => 'CDE Box',
                'kapasitas' => '2.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'cde-box.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 3001 CDD',
                'jenis_kendaraan' => 'CDD Bak',
                'kapasitas' => '4.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'cdd-bak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 3002 CDD',
                'jenis_kendaraan' => 'CDD Box',
                'kapasitas' => '4.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'cdd-box.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 4001 FUSO',
                'jenis_kendaraan' => 'Fuso Bak',
                'kapasitas' => '7 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'fuso-bak.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 4002 FUSO',
                'jenis_kendaraan' => 'Fuso Box',
                'kapasitas' => '7 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'fuso-box.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 5001 TRON',
                'jenis_kendaraan' => 'Tronton Wings Box',
                'kapasitas' => '10.5 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'tronton-wings.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 6001 TRL',
                'jenis_kendaraan' => 'Truck Trailer',
                'kapasitas' => '20 Ton',
                'harga_sewa_per_hari' => 850000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Angkutan',
                'gambar' => 'truck-trailer.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ========== SAMPAH / DUMP TRUCK ==========
            [
                'no_plat' => 'B 7001 DMP',
                'jenis_kendaraan' => 'CDD Dump Truck',
                'kapasitas' => '6 Ton',
                'harga_sewa_per_hari' => 400000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Sampah',
                'gambar' => 'dump-cdd.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 7002 CDE',
                'jenis_kendaraan' => 'CDE Dump',
                'kapasitas' => '2.5 Ton',
                'harga_sewa_per_hari' => 300000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Sampah',
                'gambar' => 'dump-cde.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ========== RENTAL / SEWA KENDARAAN (HARIAN) ==========
            [
                'no_plat' => 'B 8001 AV',
                'jenis_kendaraan' => 'Avanza (Regular)',
                'kapasitas' => '7 Orang',
                'harga_sewa_per_hari' => 350000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'avanza.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 8002 AV',
                'jenis_kendaraan' => 'Avanza (Regular)',
                'kapasitas' => '7 Orang',
                'harga_sewa_per_hari' => 350000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'avanza.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 8003 IN',
                'jenis_kendaraan' => 'Inova (Regular)',
                'kapasitas' => '8 Orang',
                'harga_sewa_per_hari' => 350000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'inova.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 8004 IN',
                'jenis_kendaraan' => 'Inova (Regular)',
                'kapasitas' => '8 Orang',
                'harga_sewa_per_hari' => 350000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'inova.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 8005 ELF',
                'jenis_kendaraan' => 'Elf (Regular)',
                'kapasitas' => '14 Orang',
                'harga_sewa_per_hari' => 350000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'elf.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 9001 BUS',
                'jenis_kendaraan' => 'Bus Medium (XL)',
                'kapasitas' => '25 Orang',
                'harga_sewa_per_hari' => 450000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'bus-medium.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // ========== RENTAL BULANAN (MONTHLY PACKAGE) ==========
            [
                'no_plat' => 'B 10001 CDD-BUL',
                'jenis_kendaraan' => 'CDD Bak (Bulanan)',
                'kapasitas' => '4.5 Ton',
                'harga_sewa_per_hari' => 10000000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'cdd-bak-bulanan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 10002 CDD-BUL',
                'jenis_kendaraan' => 'CDD Box (Bulanan)',
                'kapasitas' => '4.5 Ton',
                'harga_sewa_per_hari' => 12000000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'cdd-box-bulanan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 10003 CDE-BUL',
                'jenis_kendaraan' => 'CDE Bak (Bulanan)',
                'kapasitas' => '2.5 Ton',
                'harga_sewa_per_hari' => 7000000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'cde-bak-bulanan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_plat' => 'B 10004 PK-BUL',
                'jenis_kendaraan' => 'Pickup (Bulanan)',
                'kapasitas' => '1.5 Ton',
                'harga_sewa_per_hari' => 4500000,
                'status_ketersediaan' => 'Tersedia',
                'layanan' => 'Rental',
                'gambar' => 'pickup-bulanan.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}

